import car from "../assets/cheuffeur-menu-cars/HatchBacks.png"

export const demoData = [
    {   img:car,
        name:'Suzuki Swift MT',
        Hourly_pack :175,
        Alloted_km :10,
        Zero_Mileage : 1250.00,
        Per_kilometre : 8.00,
        FUP:'Suzuki Swift MT',
        true_unlimited :175,
        security_deposit : 1250.00,
        fuel_type : 'Petrol',
    },
    {   img:car,
        name:'Suzuki Swift MT',
        Hourly_pack :175,
        Alloted_km :10,
        Zero_Mileage : 1250.00,
        Per_kilometre : 8.00,
        FUP:'Suzuki Swift MT',
        true_unlimited :175,
        security_deposit : 1250.00,
        fuel_type : 'Petrol',
    },
    {   img:car,
        name:'Suzuki Swift MT',
        Hourly_pack :175,
        Alloted_km :10,
        Zero_Mileage : 1250.00,
        Per_kilometre : 8.00,
        FUP:'Suzuki Swift MT',
        true_unlimited :175,
        security_deposit : 1250.00,
        fuel_type : 'Petrol',
    },
    {   img:car,
        name:'Suzuki Swift MT',
        Hourly_pack :175,
        Alloted_km :10,
        Zero_Mileage : 1250.00,
        Per_kilometre : 8.00,
        FUP:'Suzuki Swift MT',
        true_unlimited :175,
        security_deposit : 1250.00,
        fuel_type : 'Petrol',
    },
]