
export const CREATE_BOOKING_REQUEST = 'CREATE_BOOKING_REQUEST';
export const CREATE_BOOKING_SUCCESS = 'CREATE_BOOKING_SUCCESS';
export const CREATE_BOOKING_FAILURE = 'CREATE_BOOKING_FAILURE';

export const FETCH_ALL_BOOKINGS_REQUEST = 'FETCH_ALL_BOOKINGS_REQUEST';
export const FETCH_ALL_BOOKINGS_SUCCESS = 'FETCH_ALL_BOOKINGS_SUCCESS';
export const FETCH_ALL_BOOKINGS_FAILURE = 'FETCH_ALL_BOOKINGS_FAILURE';

export const FETCH_BOOKING_BY_ID_REQUEST = 'FETCH_BOOKING_BY_ID_REQUEST';
export const FETCH_BOOKING_BY_ID_SUCCESS = 'FETCH_BOOKING_BY_ID_SUCCESS';
export const FETCH_BOOKING_BY_ID_FAILURE = 'FETCH_BOOKING_BY_ID_FAILURE';

export const UPDATE_BOOKING_REQUEST = 'UPDATE_BOOKING_REQUEST';
export const UPDATE_BOOKING_SUCCESS = 'UPDATE_BOOKING_SUCCESS';
export const UPDATE_BOOKING_FAILURE = 'UPDATE_BOOKING_FAILURE';

export const DELETE_BOOKING_REQUEST = 'DELETE_BOOKING_REQUEST';
export const DELETE_BOOKING_SUCCESS = 'DELETE_BOOKING_SUCCESS';
export const DELETE_BOOKING_FAILURE = 'DELETE_BOOKING_FAILURE';
